services:
  - type: web
    name: omar-eshaq-digital-card
    runtime: static
    repo: https://github.com/Eshaq7/omar-eshaq-digital-card
    branch: main
    buildCommand: echo "Using prebuilt static files"
    staticPublishPath: ./docs
    autoDeployTrigger: commit
    renderSubdomainPolicy: enabled
  - type: web
    name: omar-eshaq-luminous-card
    runtime: static
    repo: https://github.com/Eshaq7/omar-eshaq-digital-card
    branch: main
    buildCommand: echo "Using prebuilt luminous static files"
    staticPublishPath: ./docs-light
    autoDeployTrigger: commit
    renderSubdomainPolicy: enabled
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
